name: streak_your_life
description: streak_your_life supports you with keeping track of and reinforcing recurring activities.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^8.0.2
  # Bloc for state management
  flutter_bloc: ^8.1.6
  # Functional programming thingies
  dartz: ^0.10.1
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
