name: streak_your_life
description: streak_your_life supports you with keeping track of and reinforcing recurring activities.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation.
  get_it: ^8.0.2
  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern.
  flutter_bloc: ^8.1.6
  # Functional programming thingies
  dartz: ^0.10.1
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5
  # Extremely fast, easy to use, and fully async NoSQL database for Flutter.
  isar: ^3.1.0+1
  # Isar Core binaries for the Isar Database.
  isar_flutter_libs: ^3.1.0+1
  # Flutter plugin for getting commonly used locations on host platform file systems.
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # A mock framework inspired by Mockito with APIs for Fakes, Mocks, behavior verification, and stubbing.
  mockito: ^5.4.4
  # Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  flutter_lints: ^5.0.0
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
